/**
 * Build script for compiling skills into a static registry.
 *
 * Scans /skills directory for SKILL.md files, parses YAML frontmatter,
 * and generates a TypeScript registry file that can be imported at runtime.
 *
 * Run: npx tsx scripts/build-skills.ts
 */

import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

const SKILLS_DIR = path.join(process.cwd(), 'skills');
const OUTPUT_FILE = path.join(process.cwd(), 'lib/generated/skills-registry.ts');

interface SkillData {
  name: string;
  description: string;
  content: string;
}

function buildSkillsRegistry() {
  const skills: Record<string, SkillData> = {};

  if (!fs.existsSync(SKILLS_DIR)) {
    console.log('No skills directory found, creating empty registry');
    writeRegistry(skills);
    return;
  }

  const entries = fs.readdirSync(SKILLS_DIR, { withFileTypes: true });
  const skillDirs = entries.filter((d) => d.isDirectory()).map((d) => d.name);

  for (const skillDir of skillDirs) {
    const skillPath = path.join(SKILLS_DIR, skillDir, 'SKILL.md');

    if (!fs.existsSync(skillPath)) {
      console.warn(`Skipping ${skillDir}: no SKILL.md found`);
      continue;
    }

    const raw = fs.readFileSync(skillPath, 'utf8');
    const { data, content } = matter(raw);

    if (!data.name || !data.description) {
      console.error(`Invalid skill ${skillDir}: missing 'name' or 'description' in frontmatter`);
      process.exit(1);
    }

    skills[data.name] = {
      name: data.name,
      description: data.description,
      content: content.trim(),
    };

    console.log(`Compiled skill: ${data.name}`);
  }

  writeRegistry(skills);
}

function writeRegistry(skills: Record<string, SkillData>) {
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: npx tsx scripts/build-skills.ts
// Source: /skills/*/SKILL.md

export interface Skill {
  name: string;
  description: string;
  content: string;
}

export const SKILLS: Record<string, Skill> = ${JSON.stringify(skills, null, 2)};

export const SKILL_NAMES = ${JSON.stringify(Object.keys(skills))} as const;
`;

  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`Generated ${OUTPUT_FILE} (${Object.keys(skills).length} skills)`);
}

buildSkillsRegistry();
